### ISSUE TITLE
Rviz上に表示するためのdescriptionとdaeファイル等３Dモデルはないのでしょうか？

### ISSUE THREAD

**Issue by luvwinnie** [CuboRex-Development/cugo_ros_control#6]
Rviz上で、Navigation2 でTF Frames等の展開するんですけど、それらのファイルは提供されていないのでしょうか？

今後は自前の64GBのJetson AGX Orin に展開する予定をしております。

**Comment by abudori3939** [comment]
お問い合わせありがとうございます。
社内でGazeboで動作するもののモデルはありますが、現在公開できるレベルまでは至っておりません。もし必要であればご返信ください。お送りいたします。
